[project]
name = "flashrnn"
version = "1.0.6"
authors = [
  { name="Korbinian Pöppel", email="korbinian.poeppel@nx-ai.com" },
  { name="Maximilian Beck", email="maximilian.beck@nx-ai.com" },
]
description = "FlashRNN: Optimizing Traditional RNNs on Modern Hardware"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
requires-python = ">=3.8"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "torch",
    "einops",
    "triton; sys_platform == 'linux'",
    "triton-windows; sys_platform == 'win32'",
    "ninja"
]


[project.urls]
Homepage = "https://github.com/NX-AI/flashrnn"
Issues = "https://github.com/NX-AI/flashrnn/issues"

[tools.setuptools.packages.find]
where = ["flashrnn"]
