[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "flashrnn"
version = "1.0.7"
authors = [
  { name="Korbinian Pöppel", email="korbinian.poeppel@nx-ai.com" },
  { name="Maximilian Beck", email="maximilian.beck@nx-ai.com" },
]
description = "FlashRNN: Optimizing Traditional RNNs on Modern Hardware"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "torch",
    "einops",
    "triton; sys_platform == 'linux'",
    "triton-windows; sys_platform == 'win32'",
    "ninja"
]


[project.urls]
Homepage = "https://github.com/NX-AI/flashrnn"
Issues = "https://github.com/NX-AI/flashrnn/issues"
"Source Code" = "https://github.com/NX-AI/flashrnn"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
namespaces = false
exclude = ["debug", "notebooks", "speed_experiments", "tests"]

[tool.setuptools.package-data]
"*" = [
    "flashrnn/gpu_info/*.cc", "flashrnn/gpu_info/*.cu", "flashrnn/gpu_info/*.h",
    "flashrnn/fused/*.cc", "flashrnn/fused/*.cu", "flashrnn/fused/*.h", "flashrnn/fused/*.cuh",
    "flashrnn/alternating/*.cc", "flashrnn/alternating/*.cu", "flashrnn/alternating/*.h", "flashrnn/alternating/*.cuh",
    "flashrnn/util/*.cc", "flashrnn/util/*.cu", "flashrnn/util/*.h", "flashrnn/util/*.cuh",
]
